/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignsRouteImport } from './routes/signs'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as MagneticsRouteImport } from './routes/magnetics'
import { Route as LetteringRouteImport } from './routes/lettering'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SignsRoute = SignsRouteImport.update({
  id: '/signs',
  path: '/signs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const MagneticsRoute = MagneticsRouteImport.update({
  id: '/magnetics',
  path: '/magnetics',
  getParentRoute: () => rootRouteImport,
} as any)
const LetteringRoute = LetteringRouteImport.update({
  id: '/lettering',
  path: '/lettering',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banners': typeof BannersRoute
  '/lettering': typeof LetteringRoute
  '/magnetics': typeof MagneticsRoute
  '/quote': typeof QuoteRoute
  '/signs': typeof SignsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banners': typeof BannersRoute
  '/lettering': typeof LetteringRoute
  '/magnetics': typeof MagneticsRoute
  '/quote': typeof QuoteRoute
  '/signs': typeof SignsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banners': typeof BannersRoute
  '/lettering': typeof LetteringRoute
  '/magnetics': typeof MagneticsRoute
  '/quote': typeof QuoteRoute
  '/signs': typeof SignsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/banners'
    | '/lettering'
    | '/magnetics'
    | '/quote'
    | '/signs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/banners'
    | '/lettering'
    | '/magnetics'
    | '/quote'
    | '/signs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/banners'
    | '/lettering'
    | '/magnetics'
    | '/quote'
    | '/signs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BannersRoute: typeof BannersRoute
  LetteringRoute: typeof LetteringRoute
  MagneticsRoute: typeof MagneticsRoute
  QuoteRoute: typeof QuoteRoute
  SignsRoute: typeof SignsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signs': {
      id: '/signs'
      path: '/signs'
      fullPath: '/signs'
      preLoaderRoute: typeof SignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magnetics': {
      id: '/magnetics'
      path: '/magnetics'
      fullPath: '/magnetics'
      preLoaderRoute: typeof MagneticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lettering': {
      id: '/lettering'
      path: '/lettering'
      fullPath: '/lettering'
      preLoaderRoute: typeof LetteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BannersRoute: BannersRoute,
  LetteringRoute: LetteringRoute,
  MagneticsRoute: MagneticsRoute,
  QuoteRoute: QuoteRoute,
  SignsRoute: SignsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
